project_id = "mnoczwmqgignmylbvpgp"

[functions.solicitar-mais-fotos]
verify_jwt = false

[functions.portal-auth]
verify_jwt = false

[functions.portal-kpi]
verify_jwt = false

[functions.portal-extrato]
verify_jwt = false

[functions.portal-indicadores]
verify_jwt = false

[functions.portal-lancamentos]
verify_jwt = false