project_id = "mnoczwmqgignmylbvpgp"

[functions.upload-avatar]
verify_jwt = false

[functions.solicitar-mais-fotos]
verify_jwt = false

[functions.portal-auth]
verify_jwt = false

[functions.verify-totp]
verify_jwt = false

[functions.portal-kpi]
verify_jwt = false

[functions.portal-extrato]
verify_jwt = false

[functions.portal-indicadores]
verify_jwt = false

[functions.portal-lancamentos]
verify_jwt = false

[functions.enviar-cilia]
verify_jwt = true

[functions.enviar-sga-hinova]
verify_jwt = true

[functions.testar-cilia]
verify_jwt = true

[functions.webhook-cobranca-hinova]
verify_jwt = false

[functions.executar-cobranca-hinova]
verify_jwt = false

[functions.disparar-github-workflow]
verify_jwt = false

[functions.scheduler-cobranca-hinova]
verify_jwt = false

[functions.scheduler-sga-hinova]
verify_jwt = false

[functions.scheduler-mgf-hinova]
verify_jwt = false

[functions.disparar-sga-workflow]
verify_jwt = false

[functions.webhook-sga-hinova]
verify_jwt = false

[functions.disparar-mgf-workflow]
verify_jwt = false

[functions.webhook-mgf-hinova]
verify_jwt = false

[functions.enviar-whatsapp]
verify_jwt = false

[functions.enviar-whatsapp-meta]
verify_jwt = false

[functions.gerar-resumo-cobranca]
verify_jwt = true

[functions.gerar-resumo-eventos]
verify_jwt = true

[functions.webhook-whatsapp-meta]
verify_jwt = false

[functions.whatsapp-flow-engine]
verify_jwt = false

[functions.whatsapp-send-message]
verify_jwt = false

[functions.livekit-rooms]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
